// Generated by CoffeeScript 1.10.0
(function() {
  var App, Audio, Game, Politico, ajax;

  ajax = function(url, fn, respType) {
    var req;
    req = new XMLHttpRequest();
    req.open('GET', url, true);
    if (respType != null) {
      req.responseType = respType;
    }
    if (fn != null) {
      req.onload = fn.bind(null, req);
    }
    return req.send();
  };

  Politico = (function() {
    function Politico(name, unblock, img, audio) {
      this.name = name;
      this.unblock = unblock;
      this.img = "img/" + img + ".png";
      this.audio = "audio/" + audio + ".mp3";
      this.audioKey = audio;
    }

    Politico.prototype.blocked = true;

    return Politico;

  })();

  Game = (function() {
    function Game() {}

    return Game;

  })();

  Audio = (function() {
    function Audio() {}

    return Audio;

  })();

  App = (function() {
    var ael, ajaxAudio, audio, audioCtx, audioItv, audioSource, bindEvents, bodyClick, bodyMouseMove, bodyTouchMove, cacando, cacheDom, canPlaySound, countPoliticos, dist, dom, getHeight, getWidth, initAudio, initImg, mdist, mouseRange, politico, politicoIdx, politicos, repeatBtnClick, setCanPlaySound, startBtnClick, throttle;

    politico = {};

    politicoIdx = 0;

    function App() {
      App.self = this;
      cacheDom();
      bindEvents();
      initAudio();
    }

    dom = {};

    cacheDom = function() {
      dom.body = document.body;
      dom.modal = document.querySelector('.modal');
      dom.repeatBtn = dom.modal.querySelector('.btn');
      dom.startModal = document.querySelector('.start-modal');
      dom.polListStart = dom.startModal.querySelectorAll('.pol-list li');
      return dom.startBtn = dom.startModal.querySelector('.btn');
    };

    bindEvents = function() {
      ael(document, 'mousemove', throttle(bodyMouseMove, 80));
      ael(document, 'touchmove', throttle(bodyTouchMove, 80));
      ael(dom.body, 'click', bodyClick);
      ael(dom.repeatBtn, 'click', repeatBtnClick);
      ael(dom.startBtn, 'click', startBtnClick);
      return dom.polListStart.forEach((function(li) {
        return ael(li, 'click', (function(e) {
          politicoIdx = parseInt(e.target.dataset.pol);
          dom.startModal.querySelector('.active').classList.remove('active');
          return li.classList.add('active');
        }));
      }));
    };

    App.prototype.hideModal = function() {
      return dom.modal.classList.add('hidden');
    };

    App.prototype.showModal = function() {
      return dom.modal.classList.remove('hidden');
    };

    App.prototype.toggleModal = function() {
      return dom.modal.classList.toggle('hidden');
    };

    ael = function(d, e, l) {
      return d.addEventListener(e, l);
    };

    throttle = function(f, d) {
      var t;
      t = false;
      return function() {
        if (t) {
          return;
        }
        t = true;
        setTimeout((function() {
          return t = false;
        }), d);
        return f.apply(null, arguments);
      };
    };

    dist = function(x0, y0, x1, y1) {
      var dx, dy;
      dx = x1 - x0;
      dy = y1 - y0;
      return Math.sqrt(dx * dx + dy * dy);
    };

    mouseRange = [50, 300, 600, 1000];

    mdist = mouseRange[1];

    cacando = false;

    bodyMouseMove = function(arg) {
      var x, y;
      x = arg.clientX, y = arg.clientY;
      if (!cacando) {
        return;
      }
      mdist = dist(x, y, politico.x, politico.y);
      if (mdist < mouseRange[0]) {
        return dom.body.style.cursor = 'pointer';
      } else {
        return dom.body.style.cursor = '';
      }
    };

    bodyTouchMove = function(arg) {
      var a;
      a = arg.touches[0];
      return bodyMouseMove(a);
    };

    bodyClick = function() {
      if (!cacando) {
        return;
      }
      if (mdist < mouseRange[0]) {
        dom.body.style.removeProperty('background');
        dom.body.style.removeProperty('cursor');
        App.self.makePoliticoImg();
        countPoliticos++;
        setTimeout(App.self.showModal, 1000);
        cacando = false;
        return mdist = mouseRange.s + 1;
      }
    };

    startBtnClick = function() {
      cacando = true;
      dom.startModal.classList.add('hidden');
      setTimeout((function() {
        return dom.startModal.remove();
      }), 800);
      return App.self.makePolitico();
    };

    repeatBtnClick = function() {
      if (cacando) {
        return;
      }
      setTimeout((function() {
        return cacando = true;
      }), 800);
      App.self.removePoliticoImg();
      App.self.makePolitico();
      return App.self.hideModal();
    };

    getWidth = function() {
      return Math.max(document.documentElement.clientWidth, window.innerWidth || 0);
    };

    getHeight = function() {
      return Math.max(document.documentElement.clientHeight, window.innerHeight || 0);
    };

    countPoliticos = 0;

    politicos = [new Politico('Temer', 0, 'temer', 'beep'), new Politico('Dilma', 5, 'Dilma', 'beep'), new Politico('Cunha', 10, 'Cunha', 'beep')];

    App.prototype.makePolitico = function() {
      var h, w;
      w = getWidth();
      h = getHeight();
      politico = politicos[politicoIdx];
      console.log(politicos);
      politico.x = Math.floor(Math.random() * (w - 100) + 100);
      politico.y = Math.floor(Math.random() * (h - 100) + 100);
      return console.info(politico.name + " " + politico.x + " " + politico.y + " " + politico.img + " " + politico.audio);
    };

    App.prototype.makePoliticoImg = function() {
      var img;
      img = document.createElement('img');
      img.setAttribute('src', politico.img);
      img.classList.add('polImg');
      img.style.left = politico.x + "px";
      img.style.top = politico.y + "px";
      return dom.body.appendChild(img);
    };

    App.prototype.removePoliticoImg = function() {
      var polImg;
      polImg = document.querySelector('.polImg');
      if (polImg) {
        return polImg.remove();
      }
    };

    audio = {};

    App.prototype.getAudio = function() {
      return audio;
    };

    audioItv = void 0;

    audioCtx = void 0;

    audioSource = void 0;

    ajaxAudio = function(url, key) {
      return ajax(url, (function(req) {
        return audioCtx.decodeAudioData(req.response, (function(buff) {
          return audio[key] = buff;
        }));
      }), 'arraybuffer');
    };

    initAudio = function() {
      var error;
      try {
        window.AudioContext = window.AudioContext || window.webkitAudioContext;
        audioCtx = new window.AudioContext();
        ajaxAudio('audio/beep.mp3', 'beep');
        return audioItv = setInterval(App.self.playSound, 100);
      } catch (error) {
        return alert('Web Audio API não é suportado em seu browser');
      }
    };

    canPlaySound = true;

    setCanPlaySound = function() {
      return canPlaySound = true;
    };

    App.prototype.playSound = function() {
      if (!canPlaySound || !cacando) {
        return;
      }
      if (mdist < mouseRange[0]) {
        setTimeout(setCanPlaySound, 150);
      } else if (mdist < mouseRange[1]) {
        setTimeout(setCanPlaySound, 300);
      } else if (mdist < mouseRange[2]) {
        setTimeout(setCanPlaySound, 500);
      } else {
        setTimeout(setCanPlaySound, 800);
      }
      canPlaySound = false;
      audioSource = audioCtx.createBufferSource();
      audioSource.buffer = audio[politico.audioKey];
      audioSource.connect(audioCtx.destination);
      return audioSource.start(0);
    };

    initImg = function() {
      var i, len, pol, results;
      results = [];
      for (i = 0, len = politicos.length; i < len; i++) {
        pol = politicos[i];
        results.push(ajax(pol.img));
      }
      return results;
    };

    return App;

  })();

  this.addEventListener('load', function() {
    return window.app = new App();
  });

}).call(this);
